name = "owari-shop"
workers_dev = true
compatibility_date = "2023-01-15"
main = "build/worker/shim.mjs"

vars.WORKERS_RS_VERSION = "0.3.0"
vars.WILDCARDSUBDOMAIN_DOMAIN = "owari.shop"
vars.WILDCARDSUBDOMAIN_FONT = "font.ttf"
vars.WILDCARDSUBDOMAIN_TOP_HALF_TEXT = "おわ"
vars.WILDCARDSUBDOMAIN_BOTTOM_HALF_TEXT = "りや"
vars.WILDCARDSUBDOMAIN_HEIGHT = "256"
vars.WILDCARDSUBDOMAIN_WIDTH = "256"
vars.WILDCARDSUBDOMAIN_BACKGROUND_COLOR = "#c0c0c0ff"
vars.WILDCARDSUBDOMAIN_FONT_COLOR = "#000000ff"

routes = [
    "owari.shop/*",
    "*.owari.shop/*",
]

[build]
command = "cargo install -q worker-build && worker-build --release" # required

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "owari-shop"
preview_bucket_name = "owari-shop"

# read more about configuring your Worker via wrangler.toml at:
# https://developers.cloudflare.com/workers/cli-wrangler/configuration
